# Generated by Django 5.0.6 on 2024-06-04 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id_application', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id_auditor', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'auditor',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='core.application')),
                ('auditor', models.ForeignKey(db_column='auditor_id', on_delete=django.db.models.deletion.CASCADE, to='core.auditor')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id_operationlog', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(db_column='auditor_id', on_delete=django.db.models.deletion.CASCADE, to='core.auditor')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
            options={
                'db_table': 'operationlog',
            },
        ),
    ]
