# Generated by Django 5.0.6 on 2024-06-04 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='application',
            field=models.ForeignKey(db_column='id_application', on_delete=django.db.models.deletion.CASCADE, to='core.application'),
        ),
        migrations.AlterField(
            model_name='task',
            name='auditor',
            field=models.ForeignKey(db_column='id_auditor', on_delete=django.db.models.deletion.CASCADE, to='core.auditor'),
        ),
    ]
